#!/usr/bin/env bash
# Install nginx web server, configuring it to listen on port 80
# and configuring nginx's index page to print "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
