#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/ permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx start
