#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html

link="https://www.youtube.com/watch?v=PCfiqY05BpA"
redir_ect="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

sudo sed -i "s|server_name\ _;|$redir_ect|" /etc/nginx/sites-available/default
sudo service nginx restart
