#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header (on web-01 and web-02)

entry="add_header X-Served-By $HOSTNAME;";
redirect="http {\n\t$entry"
sudo sed -i "s|http {|$redirect|" /etc/nginx/nginx.conf
sudo service nginx restart
