#!/usr/bin/env bash
# Bash script for reconfiguring the listening port
# on an nginx server

# sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
#sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart 
