#!/usr/bin/env bash
# Write a script that:
# - Create file /var/run/myscript.pid containing its PID.
# - Displays "To infinity and beyond" indefinitely.
# - Displays "I hate the kill command" on SIGTERM signal.
# - Displays "Y U no love me?!" on SIGINT signal.
# - Deletes file `/var/run/myscript.pid` 
# 	and terminates on SIGQUIT or SIGTERM signal.

echo $$ > /var/run/myscript.pid

trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
