#!/usr/bin/env bash
# script that displays the visitor IP along with
# the HTTP status code from the Apache log file
#  Groups visitors by IP and HTTP status code.
#  Displays the number of occurrences, IP, and HTTP status
#  code of each log, in sorted order.

file="./apache-access.log"
awk '{print $1 " " $9;}' $file | sort | uniq -c | sort -nr
