#!/usr/bin/env bash
# loops from 1 to 20, displaying $i,
#"bad luck from china" after 4th loop
#"bad luck from Japan" after 9th loop
#"bad luck from Italy" after 17th loop

i=1
while [[ $i -le 20 ]]
do
	echo $i
    	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
    	esac
    	((i++))
done
