#!/usr/bin/env bash
# loops from 1 to 20, displaying $i,
#"bad luck from china" after 4th loop
#"bad luck from Japan" after 9th loop
#"bad luck from Italy" after 17th loop

i=1
while [[ $i -le 20 ]]
do
	echo $i
	if [[ $i -eq 4 ]]; then
		echo "bad luck from China"
	elif [[ $i -eq 9 ]]; then
		echo "bad luck from Japan"
	elif [[ $i -eq 17 ]]; then
		echo "bad luck from Italy"
	fi
	((i++))
done
